#generates random .aut files
from random import *
import string
import sys
import os

n = 100;

if(len(sys.argv) == 1):
    print "This requires one argument"
    sys.exit(1)

outDir = sys.argv[1]

for i in range(n):
  random = Random()
  random.seed(i)

  xLow = random.randint(-50,50)
  xHigh = random.randint(-50,50)
  if(xLow > xHigh):
      tmp = xLow
      xLow = xHigh
      xHigh = tmp

  yLow = random.randint(-50,50)
  yHigh = random.randint(-50,50)
  if(yLow > yHigh):
      tmp = yLow
      yLow = yHigh
      yHigh = tmp

  f = open(outDir + "/test" + str(i) + ".aut", "w")

  f.write("Xrange " + str(xLow) + " " + str(xHigh) + ";\n")
  f.write("Yrange " + str(yLow) + " " + str(yHigh) + ";\n")

  f.write('Name "Generated by Ryan mwahaha";\n')

  rd = random.randint(0,255)
  gd = random.randint(0,255)
  bd = random.randint(0,255) 
  ra = random.randint(0,255) 
  ga = random.randint(0,255) 
  ba = random.randint(0,255) 
       
  f.write("Colors (" + str(rd) + ", " + str(gd) + ", " + str(bd) + "), (" + str(ra) + ", " + str(ga) + ", " + str(ba) + ");\n")
  f.write("Chars " + random.choice(string.ascii_uppercase + string.ascii_lowercase + string.digits) + 
                     ", " + 
                     random.choice(string.ascii_uppercase + string.ascii_lowercase + string.digits)
                     + ";\n")


  f.write("Initial {\n")
  firstX = True
  yList = range(yLow, yHigh+1)
  random.shuffle(yList)
  for y in yList:
      if(random.choice([True,False])):
          f.write("Y = " + str(y) + " : ")
          xList = range(xLow, xHigh+1)
          random.shuffle(xList)
          for x in xList: 
              #also print input stuff for 308 program
                  if(firstX):
                      f.write(str(x))
                      firstX = False
                  elif(random.choice([True,False])):
                      f.write("," + str(x))
          f.write(";\n")
          firstX = True
  f.write("};\n")


    #insert randcommand.py

    #we know ranges here

    #run 308 program with it's matching input

    #crop and diff
    
  print "yo"
  oracleF = open("test308/test" + str(i) + ".308", "r")

  oracleList = [[]]
  for y in range(0, yHigh+1-yLow):
    for x in range(0, xHigh+1-xLow):
        oracleList[y][x] = oracleF.read(1)
    newline = oracleF.read(1)
  oracleF.close()

  testF = open("output/test" + str(i) + ".229")
  testPassed = True
  for y in range(wyLow-yLow, (wyLow-yLow)+(wyHigh-wyLow)+1):
      for x in range(wxLow-xLow, (wxLow-xLow)+(wxHigh-wxLow)+1):
          cell = testF.read(1)
          if((cell != liveChar && oracleList[y][x] == '1')):
              testPassed = False
              print "Test " + str(i) + " failed at window index ("+str(x)+","+str(y)+")"
          elif((cell != deadChar && oracleList[y][x] == '0')):
              testPassed = False
              print "Test " + str(i) + " failed at window index ("+str(x)+","+str(y)+")"
       returnStatement = testF.read(1)
       if(returnStatement != '\n'):
           testPassed = False
           print "Test " + str(i) + " failed at y=" + str(y) + "with no return statement"

  if(testPassed):
      print "Test " + str(i) + " passed!"







